defaults:
  - test

mode: storm            # your runner will call run_storm_experiment(cfg)


test:
  batch_size: 16
  save_raw: true
  save_results: true # This should always be true for an analysis mode.

storm:
  main_phase:
    start_index: 33
    end_index: 40